import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import "@/shared/styles/globals.css";

import { ClientProviders } from "../../client-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ClientProviders>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </ClientProviders>
      </body>
    </html>
  );
}
