import type { Metadata } from "next";

import "@/shared/styles/globals.css";
import { Box } from "@mui/material";

import { ClientProviders } from "../../client-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ClientProviders>
          <Box
            sx={{
              minHeight: "100vh",
              display: "flex",
              flexDirection: "column",
              backgroundColor: "#E7E7E7",
            }}
          >
            {children}
          </Box>
        </ClientProviders>
      </body>
    </html>
  );
}
