import { IPlace } from "../types";

export const mockPlaces: IPlace[] = [
  {
    id: 1,
    name: "Central Coffee",
    description: "Уютная кофейня в центре города с авторскими напитками.",
    address: "ул. Ленина, 10, Москва, Россия ул. Ленина, 10, Москва, Россия ул. Ленина, 10, Москва, Россия ул. Ленина, 10, Москва, Россия ул. Ленина, 10, Москва, Россия",
    lat: 55.7558,
    lon: 37.6176,
    city: {
      id: 1,
      name: "Москва",
      lat: 55.7558,
      lon: 37.6176,
      timezone: "Europe/Moscow",
    },
    website: "https://centralcoffee.example",
    tg: "@centralcoffee",
    zalo: null,
    start_time: "08:00",
    end_time: "22:00",
    is_deleted: false,
    pictures: [
      "https://picsum.photos/seed/coffee1/800/600",
      "https://picsum.photos/seed/coffee2/800/600",
    ],
    interest_categories: [1, 3, 7],
  },
  {
    id: 2,
    name: "Skyline Rooftop",
    description: "Бар с панорамным видом на город.",
    address: "пр-т Мира, 25",
    lat: 55.7601,
    lon: 37.6189,
    city: {
      id: 1,
      name: "Москва",
      lat: 55.7558,
      lon: 37.6176,
      timezone: "Europe/Moscow",
    },
    website: null,
    tg: "@skylinebar",
    zalo: null,
    start_time: "18:00",
    end_time: "03:00",
    is_deleted: false,
    pictures: [
      "https://picsum.photos/seed/rooftop1/800/600",
      "https://picsum.photos/seed/rooftop2/800/600",
      "https://picsum.photos/seed/rooftop3/800/600",
    ],
    interest_categories: [2, 5],
  },
  {
    id: 3,
    name: "Art Space 404",
    description: "Креативное пространство для выставок и мероприятий.",
    address: "ул. Арбат, 42",
    lat: 55.7483,
    lon: 37.5931,
    city: {
      id: 1,
      name: "Москва",
      lat: 55.7558,
      lon: 37.6176,
      timezone: "Europe/Moscow",
    },
    website: "https://art404.example",
    tg: null,
    zalo: null,
    start_time: "10:00",
    end_time: "21:00",
    is_deleted: false,
    pictures: [
      "https://picsum.photos/seed/art1/800/600",
      "https://picsum.photos/seed/art2/800/600",
    ],
    interest_categories: [4, 6, 9],
  },
];
